<?php

/** @var \Magento\Backend\Block\Template $block */
/** @var \Itonomy\Katanapim\ViewModel\ImportScheduleProvider $logProvider */
/** @var \Magento\Framework\Escaper $escaper */

$logProvider = $block->getlogProvider();
$logs = $logProvider->getImportJobs();
?>

<h2>
    <span><?= $block->escapeHtml(__('Recent import jobs')); ?></span>
</h2>

<div>
    <table class="data-grid">
        <thead>
        <tr class="headings">
            <th class="data-grid-th"><?= $escaper->escapeHtml(__('Job Name')) ?></th>
            <th class="data-grid-th"><?= $escaper->escapeHtml(__('Cron Job Messages')) ?></th>
            <th class="data-grid-th"><?= $escaper->escapeHtml(__('Scheduled At ')) ?></th>
            <th class="data-grid-th"><?= $escaper->escapeHtml(__('Cronjob Status')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($logs as $log): ?>
            <tr>
                <td data-th="<?= $escaper->escapeHtmlAttr(__('Job Name')) ?>"
                    class="row"><?= $escaper->escapeHtml($logProvider->getImportJobName($log->getJobCode())) ?></td>
                <td data-th="<?= $escaper->escapeHtmlAttr(__('CronJob Messages')) ?>"
                    class="row"><?= $escaper->escapeHtml($log->getMessages()) ?></td>
                <td data-th="<?= $escaper->escapeHtmlAttr(__('Scheduled At')) ?>"
                    class="row"><?= $escaper->escapeHtml($log->getScheduledAt()) ?></td>
                <td data-th="<?= $escaper->escapeHtmlAttr(__('Cronjob Status')) ?>"
                    class="row"><?= $escaper->escapeHtml($log->getStatus()) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

    <div class="imports-additional-info">
        <?= $escaper->escapeHtml(__(
            'The information here represents magento cronjobs. For more detailed information on imports see '
        )) ?>
        <span class="logfile-path">
            <?= $escaper->escapeHtml('[..]/var/log/katanapim/system.log') ?>
        </span>
    </div>
</div>
