<?php
/**
 * @var $block \Itonomy\Katanapim\Block\Adminhtml\LogListing
 */

 $collection = $block->getLogListing();
?>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
    <?php if (!empty($collection)) { ?>
    <tr>
        <td>
            <table border="1" width="100%" cellspacing="1" cellpadding="1">
                <tr style="font-size: 16px;height: 50px;">
                    <th width="5%">Log Type</th>
                    <th width="75%">Log Text</th>
                    <th width="20%">Log Entity Type</th>
                </tr>
                <?php foreach ($collection as $item) { ?>
                    <tr style="height:45px; text-indent:10px;">
                        <td>
                            <textarea class="value-container" readonly><?php echo $block->escapeHtml($item['log_type']); ?></textarea>
                        </td>
                        <td>
                            <textarea class="value-container" readonly><?php echo $block->escapeHtml($item['log_text']); ?></textarea>
                        </td>
                        <td>
                            <textarea class="value-container" readonly><?php echo $block->escapeHtml($item['log_entity_type']); ?></textarea>
                        </td>
                    </tr>
                <?php  } ?>
            </table>
        </td>
    </tr>
    <?php } ?>
</table>
